/**
 * Artisan: Authentic Pre-seeded Indian Artisan Crafts
 * Curated showcasing diverse geographical indications (GI),
 * traditional craft forms, and transparent fair-pricing breakdowns.
 */

export const INITIAL_ARTISANS = [
  {
    id: "artisan-1",
    fullName: "Sitadevi Devi",
    phone: "+91 98765 43210",
    email: "sitadevi.mithila@example.com",
    state: "Bihar",
    districtVillage: "Ranti Village, Madhubani",
    craftSpecialty: "Madhubani (Mithila) Folk Painting",
    craftTradition: "Bharni & Kachni style on handmade paper using bamboo twigs & natural dyes",
    yearsExperience: 28,
    upiId: "sitadevi@upi",
    bio: "National Awardee artisan practicing Madhubani painting passed down through 4 generations of Mithila women. Specializes in Kohbar and sacred nature motifs.",
    profileImage: "/assets/sitadevi_profile.jpg",
    isVerified: true,
    hasGiTag: true,
    preferredLanguage: "hi"
  },
  {
    id: "artisan-2",
    fullName: "Rameshwar Acharya",
    phone: "+91 94123 88765",
    email: "rameshwar.channapatna@example.com",
    state: "Karnataka",
    districtVillage: "Channapatna, Ramanagara",
    craftSpecialty: "Channapatna Lacquer Wooden Toys",
    craftTradition: "Wrightia tinctoria (Aale mara) wood turned on lathe with natural lac and vegetable dyes",
    yearsExperience: 19,
    upiId: "rameshwar.toys@upi",
    bio: "Master artisan preserving Tipu Sultan era Channapatna woodcraft. 100% non-toxic, child-safe toys colored with turmeric, indigo, and kumkum.",
    profileImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    isVerified: true,
    hasGiTag: true,
    preferredLanguage: "kn"
  },
  {
    id: "artisan-3",
    fullName: "Kailash Chand Kumhar",
    phone: "+91 98290 11234",
    email: "kailash.bluepottery@example.com",
    state: "Rajasthan",
    districtVillage: "Kot Jewar, Jaipur",
    craftSpecialty: "Jaipur Traditional Blue Pottery",
    craftTradition: "Non-clay quartz pottery with copper oxide and cobalt mineral glazes fired at low temperature",
    yearsExperience: 22,
    upiId: "kailash.pottery@upi",
    bio: "Carrying on the Turko-Persian craft introduced by Maharaja Sawai Ram Singh II. Creates hand-painted ceramic vases and decorative wall plates.",
    profileImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
    isVerified: true,
    hasGiTag: true,
    preferredLanguage: "hi"
  },
  {
    id: "artisan-4",
    fullName: "Budhram Baghel",
    phone: "+91 97555 67890",
    email: "budhram.dhokra@example.com",
    state: "Chhattisgarh",
    districtVillage: "Kondagaon, Bastar",
    craftSpecialty: "Bastar Dhokra Lost-Wax Bell Metal Craft",
    craftTradition: "Ancient 4000-year-old Indus Valley lost-wax casting using beeswax, river clay, and recycled brass",
    yearsExperience: 31,
    upiId: "budhram.bastar@upi",
    bio: "Tribal master craftsman preserving the ancient Dhokra casting technique. Each piece is unique as the clay mold must be broken to retrieve the sculpture.",
    profileImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80",
    isVerified: true,
    hasGiTag: true,
    preferredLanguage: "hi"
  }
];

export const INITIAL_PRODUCTS = [
  {
    id: "prod-1",
    artisanId: "artisan-1",
    title: "Handmade Madhubani 'Tree of Life' Folk Art on Handmade Paper (14x18 in)",
    titleRegional: {
      hi: "हस्तनिर्मित मधुबनी 'जीवन का वृक्ष' लोक चित्रकला (14x18 इंच)",
      bn: "হস্তনির্মিত মধুবনী 'জীবনের গাছ' লোকশিল্প (14x18 ইঞ্চি)",
      mr: "हस्तनिर्मित मधुबनी 'जीवनाचा वृक्ष' लोककला (14x18 इंच)",
      ta: "கைவினை மதுபானி 'வாழ்வின் மரம்' நாட்டுப்புற ஓவியம் (14x18 இன்ச்)",
      te: "చేతితో వేసిన మధుబని 'జీవన వృక్షం' జానపద కళ (14x18 అంగుళాలు)",
      gu: "હસ્તનિર્મિત મધુબની 'જીવનનું વૃક્ષ' લોકકળા (14x18 ઇંચ)",
      kn: "ಕೈಯಿಂದ ರಚಿಸಿದ ಮಧುಬನಿ 'ಜೀವನದ ಮರ' ಜಾನಪದ ಚಿತ್ರಕಲೆ (14x18 ಇಂಚು)",
      od: "ହସ୍ତକୃତ ମଧୁବନୀ 'ଜୀବନର ବୃକ୍ଷ' ଲୋକଚିତ୍ର (14x18 ଇଞ୍ଚ)"
    },
    category: "Paintings & Folk Art",
    materials: ["Handmade Cotton Rag Paper", "Natural Mineral Pigments", "Neem Twig Inks", "Organic Gum"],
    primaryColors: ["Ochre Yellow", "Indigo Blue", "Madder Red", "Lampblack"],
    craftTechnique: "Bharni Style Hand-Linework using Nib and Bamboo sticks",
    dimensions: "14 x 18 inches (Unframed)",
    weightGrams: 150,
    description: "An authentic, hand-painted Madhubani artwork depicting the sacred Kalpavriksha (Tree of Life) intertwined with peacocks, songbirds, and floral motifs. Painted using age-old organic dyes extracted from turmeric, indigo, crushed marigold, and soot on acid-free handmade paper.",
    culturalStory: "Practiced for centuries by women of the Mithila region in Bihar, Madhubani paintings were traditionally done on mud walls during celebrations. The Tree of Life symbolizes the cosmic balance of nature, fertility, and eternal peace.",
    careInstructions: "Keep framed under anti-reflective glass. Protect from direct moisture and persistent ultraviolet sunlight.",
    tags: ["Madhubani", "GI-Tagged", "Mithila", "Eco-Friendly", "Natural Dyes", "Wall Decor"],
    
    // Fair Pricing Breakdown
    materialCost: 320,
    laborHours: 24,
    hourlyRate: 85,
    overheadCost: 150,
    profitMarginPercent: 25,
    finalPrice: 2850,
    marketBenchmarkPrice: 4200,

    imageUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80",
    enhancedImageUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80",
    backgroundStyle: "studio_white",
    stockQuantity: 3,
    isInStock: true,
    isApprovedByArtisan: true,
    originState: "Bihar",
    hasGiTag: true,
    createdAt: "2026-03-01T10:00:00Z"
  },
  {
    id: "prod-2",
    artisanId: "artisan-2",
    title: "Channapatna Eco-Friendly Hand-Turned Wooden Stacking Ring Toy",
    titleRegional: {
      hi: "चनापटना पर्यावरण-अनुकूल प्राकृतिक लकड़ी का स्टैकिंग रिंग खिलौना",
      bn: "চান্নাপাটনা পরিবেশ-বান্ধব কাঠের স্ট্যাকিং রিং খেলনা",
      mr: "चन्नापटना पर्यावरण-पूरक लाकडी रिंग खेळणे",
      ta: "சன்னபட்னா இயற்கை மர அடுக்கு வளைய பொம்மை",
      te: "చన్నపట్న పర్యావరణ అనుకూల చెక్క రింగుల బొమ్మ",
      gu: "ચન્નાપટણા ઇકો-ફ્રેન્ડલી લાકડાનું સ્ટેકિંગ રિંગ રમકડું",
      kn: "ಚನ್ನಪಟ್ಟಣ ಪರಿಸರ ಸ್ನೇಹಿ ಮರದ ರಿಂಗ್ ಆಟಿಕೆ",
      od: "ଚାନ୍ନାପାଟନା ପରିବେଶ ଅନୁକୂଳ କାଠ ଷ୍ଟାକିଂ ରିଙ୍ଗ ଖେଳଣା"
    },
    category: "Wooden Toys & Carvings",
    materials: ["Wrightia Tinctoria (Ivory Wood)", "Natural Non-Toxic Lac", "Vegetable Dyes (Turmeric, Kumkum)"],
    primaryColors: ["Sunset Orange", "Turmeric Yellow", "Leaf Green", "Natural Wood Grain"],
    craftTechnique: "Lathe Wood Turning with Hand-Applied Friction Lacquer Polish",
    dimensions: "Base Diameter 12 cm, Height 22 cm",
    weightGrams: 420,
    description: "Classic educational Montessori stacking tower crafted from locally harvested Hale wood. Polished to a smooth high-gloss finish using heat generated by palm-leaf friction and natural sealing lac. 100% lead-free and baby-safe.",
    culturalStory: "Channapatna in Karnataka is affectionately known as 'Gombegala Ooru' (Toy Town). This 200-year-old craft was nurtured by Tipu Sultan who invited Persian artisans to train local craftspeople in wood turning.",
    careInstructions: "Wipe with a clean dry cloth. Do not soak in water or use harsh chemical detergents.",
    tags: ["Channapatna", "GI-Tagged", "Montessori", "Wooden Toys", "Zero Plastic", "Organic Baby"],
    
    // Fair Pricing Breakdown
    materialCost: 180,
    laborHours: 6.5,
    hourlyRate: 90,
    overheadCost: 65,
    profitMarginPercent: 30,
    finalPrice: 980,
    marketBenchmarkPrice: 1550,

    imageUrl: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&auto=format&fit=crop&q=80",
    enhancedImageUrl: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&auto=format&fit=crop&q=80",
    backgroundStyle: "warm_terracotta",
    stockQuantity: 12,
    isInStock: true,
    isApprovedByArtisan: true,
    originState: "Karnataka",
    hasGiTag: true,
    createdAt: "2026-03-05T12:30:00Z"
  },
  {
    id: "prod-3",
    artisanId: "artisan-3",
    title: "Jaipur Traditional Hand-Painted Floral Blue Pottery Ceramic Vase (8 inch)",
    titleRegional: {
      hi: "जयपुर पारंपरिक हस्तनिर्मित ब्लू पॉटरी सिरेमिक फूलदान (8 इंच)",
      bn: "জয়পুর ঐতিহ্যবাহী হাতে আঁকা ব্লু পটারি ফুলদানি (8 ইঞ্চি)",
      mr: "जयपूर पारंपरिक हस्तनिर्मित ब्लू पॉटरी सिरॅमिक फुलदाणी",
      ta: "ஜெய்ப்பூர் பாரம்பரிய கைவினை நீல மட்பாண்ட பூச்சாடி",
      te: "జైపూర్ సాంప్రదాయ చేతితో తయారు చేసిన బ్లూ పాట్టీ పూల కుండీ",
      gu: "જયપુર પરંપરાગત હાથથી ચિત્રિત બ્લુ પોટરી ફૂલદાની",
      kn: "ಜೈಪುರ ಸಾಂಪ್ರದಾಯಿಕ ಕೈಯಿಂದ ಚಿತ್ರಿಸಿದ ಬ್ಲೂ ಪಾಟರಿ ಹೂದಾನಿ",
      od: "ଜୟପୁର ପାରମ୍ପରିକ ହସ୍ତକୃତ ବ୍ଲୁ ପଟେରୀ ଫୁଲଦାନୀ"
    },
    category: "Ceramics & Pottery",
    materials: ["Quartz Stone Powder", "Fuller's Earth (Multani Mitti)", "Cobalt Oxide Glaze", "Glass Frit"],
    primaryColors: ["Persian Cobalt Blue", "Turquoise Cyan", "Pure White"],
    craftTechnique: "Low-heat Kiln Firing & Fine Camel-hair Brush Hand Painting",
    dimensions: "Diameter 11 cm, Height 20 cm",
    weightGrams: 650,
    description: "Unique Jaipur Blue Pottery vase crafted without clay. Made from a special paste of crushed quartz stone, glass frit, and natural gum, decorated with Persian floral arabesques and finished with a luminous glass glaze.",
    culturalStory: "Unlike standard terracotta, Jaipur Blue Pottery does not use clay and never develops cracks. Revived by royal patron Maharaja Ram Singh II, it represents the harmonic synthesis of Afghan, Persian, and Rajasthani artistry.",
    careInstructions: "Wash gently with lukewarm soapy water and soft sponge. Not microwave or dishwasher safe.",
    tags: ["Blue Pottery", "Jaipur", "GI-Tagged", "Handmade Ceramic", "Home Decor", "Cobalt Glaze"],
    
    // Fair Pricing Breakdown
    materialCost: 260,
    laborHours: 9,
    hourlyRate: 85,
    overheadCost: 110,
    profitMarginPercent: 28,
    finalPrice: 1450,
    marketBenchmarkPrice: 2200,

    imageUrl: "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?w=800&auto=format&fit=crop&q=80",
    enhancedImageUrl: "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?w=800&auto=format&fit=crop&q=80",
    backgroundStyle: "silk_velvet",
    stockQuantity: 5,
    isInStock: true,
    isApprovedByArtisan: true,
    originState: "Rajasthan",
    hasGiTag: true,
    createdAt: "2026-03-08T09:15:00Z"
  },
  {
    id: "prod-4",
    artisanId: "artisan-4",
    title: "Bastar Dhokra Lost-Wax Cast Brass Tribal Musician Figurine (7 inch)",
    titleRegional: {
      hi: "बस्तर ढोकरा लॉस्ट-वैक्स कांस्य आदिवासी संगीतकार मूर्ति (7 इंच)",
      bn: "বস্তার ঢোকরা ব্রাস আদিবাসী সংগীতশিল্পীর মূর্তি (7 ইঞ্চি)",
      mr: "बस्तर ढोकरा ब्रास आदिवासी संगीतकार मूर्ती (7 इंच)",
      ta: "பஸ்தார் டோக்ரா பித்தளை பழங்குடி இசைக்கலைஞர் சிலை",
      te: "బస్తర్ డోక్రా ఇత్తడి గిరిజన సంగీతకారుడి విగ్రహం",
      gu: "બસ્તર ઢોકરા કાંસા આદિવાસી સંગીતકાર મૂર્તિ",
      kn: "ಬಸ್ತಾರ್ ಧೋಕ್ರಾ ಹಿತ್ತಾಳೆ ಬುಡಕಟ್ಟು ಸಂಗೀತಗಾರನ ವಿಗ್ರಹ",
      od: "ବସ୍ତର ଢୋକ୍ରା ପିତ୍ତଳ ଆଦିବାସୀ ସଙ୍ଗୀତକାର ମୂର୍ତ୍ତି"
    },
    category: "Metalcraft & Bell Metal",
    materials: ["Recycled Brass Alloy", "Wild Bee Wax", "Alluvial River Bed Clay", "Coal Fuel"],
    primaryColors: ["Antique Gold", "Verdigris Patina", "Warm Bronze"],
    craftTechnique: "Lost-Wax (Cire Perdue) Solid Casting with Hand-rolled Wax Threads",
    dimensions: "Base 8x6 cm, Height 18 cm",
    weightGrams: 890,
    description: "An evocative tribal musician playing the traditional Bastar flute, cast in solid brass using the ancient non-ferrous lost-wax process. Features intricate textured filigree patterns hand-coiled from beeswax strands before molten metal pouring.",
    culturalStory: "Dhokra craft traces an unbroken 4,000-year lineage back to the 'Dancing Girl of Mohenjo-Daro'. Created by Ghadwa tribal artisans in Chhattisgarh, each creation is a one-of-a-kind collector piece because the clay mold is shattered to release the metal.",
    careInstructions: "Dust with a soft microfiber cloth. Apply brass polish or mustard oil drop occasionally to retain antique luster.",
    tags: ["Dhokra", "GI-Tagged", "Tribal Art", "Bastar", "Lost Wax", "Bell Metal", "Sculpture"],
    
    // Fair Pricing Breakdown
    materialCost: 450,
    laborHours: 16,
    hourlyRate: 85,
    overheadCost: 180,
    profitMarginPercent: 25,
    finalPrice: 2490,
    marketBenchmarkPrice: 3800,

    imageUrl: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=800&auto=format&fit=crop&q=80",
    enhancedImageUrl: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=800&auto=format&fit=crop&q=80",
    backgroundStyle: "raw_canvas",
    stockQuantity: 4,
    isInStock: true,
    isApprovedByArtisan: true,
    originState: "Chhattisgarh",
    hasGiTag: true,
    createdAt: "2026-03-10T14:20:00Z"
  }
];

export const CRAFT_CATEGORIES = [
  "All Categories",
  "Paintings & Folk Art",
  "Wooden Toys & Carvings",
  "Ceramics & Pottery",
  "Metalcraft & Bell Metal",
  "Handloom & Textiles",
  "Terracotta & Clay Art",
  "Jewelry & Filigree",
  "Leather & Jute Crafts"
];

export const INDIAN_STATES = [
  "All States",
  "Andhra Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Gujarat",
  "Himachal Pradesh",
  "Jammu & Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Tamil Nadu",
  "Telangana",
  "Uttar Pradesh",
  "West Bengal"
];
